Update linkCheckPR.yml

diff --git a/.github/workflows/linkCheckPR.yml b/.github/workflows/linkCheckPR.yml
--- a/.github/workflows/linkCheckPR.yml
+++ b/.github/workflows/linkCheckPR.yml
@@ -2,19 +2,59 @@ name: link_checkPR
 
 on:
   pull_request:
-    branches:
-      - main
+    branches: [main]
 
 jobs:
-  linkChecker:
+  check-links:
     runs-on: ubuntu-latest
-
     steps:
-      - uses: actions/checkout@v4
+      - name: Clone repository
+        uses: actions/checkout@v4
+        with:
+          fetch-depth: 0
+          ref: ${{github.event.pull_request.head.ref}}
+          repository: ${{github.event.pull_request.head.repo.full_name}}
 
-      - name: Link Checker
+      - name: Check out main branch
+        run: git checkout main
+
+      - name: Dump all links from main
+        id: dump_links_from_main
         uses: lycheeverse/lychee-action@v1
         with:
-          args: --accept=200,403,429 --base . --verbose --no-progress './**/*.md' './**/*.html' './**/*.rst'
-          token: ${{ secrets.CUSTOM_TOKEN }}
+          args: |
+            --dump
+            --include-fragments
+            .
+          output: ./links-main.txt
+
+      - name: Stash untracked files
+        run: git stash push --include-untracked
+
+      - name: Check out feature branch
+        run: git checkout ${{ github.head_ref }}
+
+      - name: Apply stashed changes
+        # Apply stashed changes, ignore errors if stash is empty
+        run: git stash pop || true
+
+      - name: Append links-main.txt to .lycheeignore
+        run: cat links-main.txt >> .lycheeignore
+
+      - name: Check links
+        uses: lycheeverse/lychee-action@v1
+        with:
+          args: |
+            --no-progress
+            --include-fragments
+            .
+          # Fail action on broken links
           fail: true
+
+      - name: Suggestions
+        if: failure()
+        run: |
+          echo -e "\nPlease review the links reported in the Check links step above."
+          echo -e "If a link is valid but fails due to a CAPTCHA challenge, IP blocking, login requirements, etc.,
+          consider adding such links to .lycheeignore file to bypass future checks.\n"
+          exit 1
